app:
  ES_ADDRESS:         # set value in environment variable
  CONFIG_FILE:        # set value in environment variable
  SLACK_CHAT_CHANNEL: # set value in environment variable

domain:
  syscheck:
    repository:
      elasticsearch:
        index:
          name: "sms-system-check"
          shardNum: 2
          replicaNum: 0
    diskcheck:
      minCapacity: "2GB"
    cpucheck:
      cpuWarningUsage: 1.0
      cpuMaximumUsage: 1.5
      cpuMinimumUsageToRemove: 0.5
