app:
  ES_ADDRESS:         # set value in environment variable
  CONFIG_FILE:        # set value in environment variable
  SLACK_CHAT_CHANNEL: # set value in environment variable

syscheck:
  diskcheck:
    minCapacity: "2GB"
  cpucheck:
    cpuWarningUsage: 1.0
    cpuMaximumUsage: 1.5
    cpuMinimumUsageToRemove: 0.5
  memorycheck:
    memoryWarningUsage: "6GB"
    memoryMaximumUsage: "7GB"
    memoryMinimumUsageToRemove: "1GB"
  repository:
    elasticsearch:
      index:
        name: "sms-system-check"
        shardNum: 2
        replicaNum: 0
  delivery:
    channel:
      pingCycle:
        diskcheck: "5m"
        cpucheck: "5m"
        memorycheck: "5m"

srvcheck:
  elasticsearch:
    targetIndices: "_all"
    maximumShardsNumber: 900
    jaegerIndexRegexp: "^jaeger-(span|service)-\\d{4}-\\d{2}-\\d{2}$"
    jaegerIndexMinLifeCycle: "720h"
  repository:
    elasticsearch:
      index:
        name: "sms-service-check"
        shardNum: 2
        replicaNum: 0
