app:
  ES_ADDRESS:         # set value in environment variable
  CONSUL_ADDRESS:     # set value in environment variable
  CONFIG_FILE:        # set value in environment variable
  SLACK_CHAT_CHANNEL: # set value in environment variable
  VERSION:            # set value in environment variable
  SMS_AWS_ID:         # set value in environment variable
  SMS_AWS_KEY:        # set value in environment variable
  SMS_AWS_REGION:     # set value in environment variable
  SMS_AWS_BUCKET:     # set value in environment variable

syscheck:
  diskcheck:
    minCapacity: "2GB"
  cpucheck:
    cpuWarningUsage: 1.0
    cpuMaximumUsage: 1.5
    cpuMinimumUsageToRemove: 0.5
  memorycheck:
    memoryWarningUsage: "6GB"
    memoryMaximumUsage: "7GB"
    memoryMinimumUsageToRemove: "1GB"
  repository:
    elasticsearch:
      index:
        name: "sms-system-check"
        shardNum: 2
        replicaNum: 0
  delivery:
    channel:
      pingCycle:
        diskcheck: "5m"
        cpucheck: "5m"
        memorycheck: "5m"

srvcheck:
  elasticsearch:
    targetIndices: "_all"
    maximumShardsNumber: 800 # default -> 900
    jaegerIndexPattern: "jaeger-*"
    jaegerIndexMinLifeCycle: "720h"
  swarmpit:
    swarmpitAppServiceName: "swarmpit_app"
    swarmpitAppMaxMemoryUsage: "600MB"
  consul:
    checkTargetServices: "announcement,auth,club,outing,schedule"
    consulServiceNameSpace: "DMS.SMS.v1.service."
    dockerServiceNameSpace: "DSM_SMS_service-"
    connCheckPingTimeOut: "2s" # default -> "5s"
  repository:
    elasticsearch:
      index:
        name: "sms-service-check"
        shardNum: 2
        replicaNum: 0
  delivery:
    channel:
      pingCycle:
        elasticsearchCheck: "12h"
        swarmpitCheck: "6h"
        consulCheck: "1m"
