version: '3.5'
services:
  health-check:
    image: jinhong0719/dms-sms-health-check:${VERSION}.RELEASE
    container_name: health-check
    networks:
      - dms-sms-local
    ports:
      - target: 8888
        published: 8888
        protocol: tcp
        mode: host
    environment:
      - VERSION=${VERSION}
      - ES_ADDRESS=${ES_ADDRESS}
      - CONFIG_FILE=${CONFIG_FILE}
      - SLACK_API_TOKEN=${SLACK_API_TOKEN}
      - SLACK_CHAT_CHANNEL=${SLACK_CHAT_CHANNEL}
    volumes:
      - ./config.yaml:/usr/share/health-check/config.yaml
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: replicated
      replicas: 1
      labels: [APP=health-check]

networks:
  dms-sms-local:
    name: dms-sms-local
    driver: overlay
