// Create package in v.1.0.0
// measure package define measurer struct about system, msg(문자 서비스) usage, etc ...
// system_measurer.go define system measurer about cpu or memory usage, disk remain capacity, etc ...

package measure
